spring.application.name=peliculas

# Puerto
server.port=${PORT:8080}

# OMDb API
omdb.api.url=${OMDB_API_URL}
omdb.api.key=${OMDB_API_KEY}

# Base de datos MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration=3600000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true